---
sudo: required

env:
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script: sudo distribution=${distribution} run_opts=${run_opts} version=${version} init=${init} ./run-tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
