---
- name: Ensure apt-https Driver is Present
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add apt-key
  apt_key:
    url: "{{ telegraf_apt_key_url }}"
    state: present

- name: Add Apt Repository
  apt_repository:
    repo: "{{ telegraf_apt_repo }}"
    update_cache: yes
  when: telegraf_install_url is not defined

- name: Install telegraf package
  package:
    name: telegraf
  when: telegraf_install_url is not defined

- name: Install from url
  get_url:
    url: "{{ telegraf_install_url }}"
    dest: /tmp/telegraf.deb
  when: telegraf_install_url is defined

- name: Install from url
  apt:
    deb: /tmp/telegraf.deb
  when: telegraf_install_url is defined
