FROM ubuntu:14.04
RUN apt-get update


# Setup base system to act like a real linux.
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get install --reinstall -y openssh-server git python-apt upstart sysvinit-utils software-properties-common
RUN mv /sbin/initctl.distrib /sbin/initctl
RUN groupadd ubuntu
RUN useradd -g ubuntu -G sudo ubuntu
RUN echo ubuntu:u | chpasswd
RUN cp -a /etc/skel /home/ubuntu
RUN chown -R ubuntu.ubuntu /home/ubuntu
RUN ln -sf /proc/mounts /etc/mtab
RUN echo "ubuntu ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu

RUN update-rc.d rsyslog defaults
RUN update-rc.d ssh defaults

RUN mkdir /home/ubuntu/.ssh
RUN chown ubuntu.ubuntu /home/ubuntu/.ssh
RUN chmod 700 /home/ubuntu/.ssh
#RUN echo "<snip>" >> /home/ubuntu/.ssh/authorized_keys
RUN echo UseDNS=no >> /etc/ssh/sshd_config

ENV HOME /home/ubuntu
EXPOSE 22 389 636 3306

ENTRYPOINT exec /sbin/init --startup-event=failsafe-boot

# Install Ansible
RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update
RUN apt-get install -y ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
